Fix translation errors in Ruby 3.x
Ruby 3 is stricter about hashes being used interchangeably with
keyword arguments, and will give errors like:

ArgumentError: wrong number of arguments (given 2, expected 0..1)

Explicitly map options hash to positional argument with ** to fix